# Generated by Django 2.0.5 on 2018-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180519_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pp',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='profile_pics/', verbose_name='Profile Photo', width_field='width_field'),
        ),
    ]
