# Generated by Django 2.0.5 on 2019-04-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
